
INPUT_FILES_LOCATION = "/Users/abhilash/Documents/Workshop/Input"
OUTPUT_FILES_LOCATION = "/Users/abhilash/Documents/Workshop/Output"

INPUT_SERVERS_LIST = "SERVERS.JSON"

INPUT_SERVERS_LIST_SERVERS = "SERVERS"
INPUT_SERVERS_LIST_ID = "ID"
INPUT_SERVERS_LIST_SERVER_NAME = "SERVER_NAME"
INPUT_SERVERS_LIST_SERVER_IP_JSON = "SERVER_IP_JSON"
INPUT_SERVERS_LIST_SERVER_OP_JSON = "SERVER_OP_JSON"
INPUT_SERVERS_LIST_SERVER_OUTPUT = "SERVER_OUTPUT"

INPUT_ROOT_MONITOR = "MONITOR"
MONITOR_LOGS = "LOGS"
MONITOR_OTHER = "OTHER"

MONITOR_LOGS_ID = "ID"
MONITOR_LOGS_FILE_NAME = "FILE_NAME"
MONITOR_LOGS_SEARCH_STRING = "SEARCH_STRING"
MONITOR_LOGS_FILE_LOCATION = "FILE_LOCATION"
MONITOR_LOGS_OUTPUT = "OUTPUT"

